name:                hscc
version:             0.1.0.0
github:              "dannypsnl/hscc"
license:             MIT
author:              "dannypsnl"
maintainer:          "dannypsnl@gmail.com"
copyright:           "2020 dannypsnl"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dannypsnl/hscc#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 1
- mtl >= 2.2
- containers >= 0.6
- megaparsec >= 8.0

library:
  source-dirs: src

executables:
  hscc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hscc

tests:
  hscc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hscc
    - hspec
    - hspec-megaparsec
