name: Racket

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup Racket
      uses: Bogdanp/setup-racket@v0.6
      with:
        architecture: 'x64'   # (x64 or x86), ignored on Linux
        distribution: 'full'  # or 'minimal'
        variant: 'regular'    # or 'CS' for Racket-on-Chez
        version: '7.6'        # or 'current' for the latest snapshot
    - run: raco pkg install --auto
    - run: raco test .
